-- Migration 32: Drop orphaned old unique constraints that migration 29 failed to drop
-- Migration 29 used wrong constraint names (e.g. 'uq_loans_coop_id') instead of the actual
-- names auto-generated by PostgreSQL (e.g. 'loans_cooperative_id_loan_id_unique').
-- Result: both old and new constraints exist. The old ones are now redundant and confusing.
-- Data check confirms no cross-submission duplicates exist, so dropping is safe.

ALTER TABLE loans DROP CONSTRAINT IF EXISTS loans_cooperative_id_loan_id_unique;
ALTER TABLE savings_accounts DROP CONSTRAINT IF EXISTS savings_accounts_cooperative_id_savings_account_id_unique;
ALTER TABLE fixed_deposits DROP CONSTRAINT IF EXISTS fixed_deposits_cooperative_id_fixed_deposit_id_unique;