/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as PrintMinistryRouteImport } from './routes/print.ministry'
import { Route as AppUsersRouteImport } from './routes/app.users'
import { Route as AppSubmissionsRouteImport } from './routes/app.submissions'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppQuestionnaireTemplatesRouteImport } from './routes/app.questionnaire-templates'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppNonFinancialDataRouteImport } from './routes/app.non-financial-data'
import { Route as AppMembersRouteImport } from './routes/app.members'
import { Route as AppInvitationsRouteImport } from './routes/app.invitations'
import { Route as AppFinancialStatementRouteImport } from './routes/app.financial-statement'
import { Route as AppFederationsRouteImport } from './routes/app.federations'
import { Route as AppDebugAuthRouteImport } from './routes/app.debug-auth'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCustomKpisRouteImport } from './routes/app.custom-kpis'
import { Route as AppCooperativesRouteImport } from './routes/app.cooperatives'
import { Route as AppBenchmarkingRouteImport } from './routes/app.benchmarking'
import { Route as AppBasicBenchmarkingRouteImport } from './routes/app.basic-benchmarking'
import { Route as AppBasicAnalyticsRouteImport } from './routes/app.basic-analytics'
import { Route as AppAuditRouteImport } from './routes/app.audit'
import { Route as AppApexesRouteImport } from './routes/app.apexes'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppUsersIndexRouteImport } from './routes/app.users.index'
import { Route as PrintFederationIdRouteImport } from './routes/print.federation.$id'
import { Route as PrintCooperativeIdRouteImport } from './routes/print.cooperative.$id'
import { Route as PrintApexIdRouteImport } from './routes/print.apex.$id'
import { Route as AppUsersApexIdRouteImport } from './routes/app.users.$apexId'
import { Route as AppSubmissionsIdRouteImport } from './routes/app.submissions_.$id'
import { Route as AppCooperativeCooperativeIdRouteImport } from './routes/app.cooperative.$cooperativeId'
import { Route as AppCooperativeProfileCooperativeIdRouteImport } from './routes/app.cooperative-profile.$cooperativeId'
import { Route as AppCooperativeMembersCooperativeIdRouteImport } from './routes/app.cooperative-members.$cooperativeId'
import { Route as AppSubmissionsIdIndexRouteImport } from './routes/app.submissions_.$id.index'
import { Route as AppSubmissionsIdQuestionnaireRouteImport } from './routes/app.submissions_.$id.questionnaire'
import { Route as AppSubmissionsIdManualEntryRouteImport } from './routes/app.submissions_.$id.manual-entry'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const PrintMinistryRoute = PrintMinistryRouteImport.update({
  id: '/print/ministry',
  path: '/print/ministry',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSubmissionsRoute = AppSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppQuestionnaireTemplatesRoute =
  AppQuestionnaireTemplatesRouteImport.update({
    id: '/questionnaire-templates',
    path: '/questionnaire-templates',
    getParentRoute: () => AppRoute,
  } as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNonFinancialDataRoute = AppNonFinancialDataRouteImport.update({
  id: '/non-financial-data',
  path: '/non-financial-data',
  getParentRoute: () => AppRoute,
} as any)
const AppMembersRoute = AppMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppRoute,
} as any)
const AppInvitationsRoute = AppInvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => AppRoute,
} as any)
const AppFinancialStatementRoute = AppFinancialStatementRouteImport.update({
  id: '/financial-statement',
  path: '/financial-statement',
  getParentRoute: () => AppRoute,
} as any)
const AppFederationsRoute = AppFederationsRouteImport.update({
  id: '/federations',
  path: '/federations',
  getParentRoute: () => AppRoute,
} as any)
const AppDebugAuthRoute = AppDebugAuthRouteImport.update({
  id: '/debug-auth',
  path: '/debug-auth',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomKpisRoute = AppCustomKpisRouteImport.update({
  id: '/custom-kpis',
  path: '/custom-kpis',
  getParentRoute: () => AppRoute,
} as any)
const AppCooperativesRoute = AppCooperativesRouteImport.update({
  id: '/cooperatives',
  path: '/cooperatives',
  getParentRoute: () => AppRoute,
} as any)
const AppBenchmarkingRoute = AppBenchmarkingRouteImport.update({
  id: '/benchmarking',
  path: '/benchmarking',
  getParentRoute: () => AppRoute,
} as any)
const AppBasicBenchmarkingRoute = AppBasicBenchmarkingRouteImport.update({
  id: '/basic-benchmarking',
  path: '/basic-benchmarking',
  getParentRoute: () => AppRoute,
} as any)
const AppBasicAnalyticsRoute = AppBasicAnalyticsRouteImport.update({
  id: '/basic-analytics',
  path: '/basic-analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppApexesRoute = AppApexesRouteImport.update({
  id: '/apexes',
  path: '/apexes',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersIndexRoute = AppUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppUsersRoute,
} as any)
const PrintFederationIdRoute = PrintFederationIdRouteImport.update({
  id: '/print/federation/$id',
  path: '/print/federation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintCooperativeIdRoute = PrintCooperativeIdRouteImport.update({
  id: '/print/cooperative/$id',
  path: '/print/cooperative/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintApexIdRoute = PrintApexIdRouteImport.update({
  id: '/print/apex/$id',
  path: '/print/apex/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersApexIdRoute = AppUsersApexIdRouteImport.update({
  id: '/$apexId',
  path: '/$apexId',
  getParentRoute: () => AppUsersRoute,
} as any)
const AppSubmissionsIdRoute = AppSubmissionsIdRouteImport.update({
  id: '/submissions_/$id',
  path: '/submissions/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCooperativeCooperativeIdRoute =
  AppCooperativeCooperativeIdRouteImport.update({
    id: '/cooperative/$cooperativeId',
    path: '/cooperative/$cooperativeId',
    getParentRoute: () => AppRoute,
  } as any)
const AppCooperativeProfileCooperativeIdRoute =
  AppCooperativeProfileCooperativeIdRouteImport.update({
    id: '/cooperative-profile/$cooperativeId',
    path: '/cooperative-profile/$cooperativeId',
    getParentRoute: () => AppRoute,
  } as any)
const AppCooperativeMembersCooperativeIdRoute =
  AppCooperativeMembersCooperativeIdRouteImport.update({
    id: '/cooperative-members/$cooperativeId',
    path: '/cooperative-members/$cooperativeId',
    getParentRoute: () => AppRoute,
  } as any)
const AppSubmissionsIdIndexRoute = AppSubmissionsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSubmissionsIdRoute,
} as any)
const AppSubmissionsIdQuestionnaireRoute =
  AppSubmissionsIdQuestionnaireRouteImport.update({
    id: '/questionnaire',
    path: '/questionnaire',
    getParentRoute: () => AppSubmissionsIdRoute,
  } as any)
const AppSubmissionsIdManualEntryRoute =
  AppSubmissionsIdManualEntryRouteImport.update({
    id: '/manual-entry',
    path: '/manual-entry',
    getParentRoute: () => AppSubmissionsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/apexes': typeof AppApexesRoute
  '/app/audit': typeof AppAuditRoute
  '/app/basic-analytics': typeof AppBasicAnalyticsRoute
  '/app/basic-benchmarking': typeof AppBasicBenchmarkingRoute
  '/app/benchmarking': typeof AppBenchmarkingRoute
  '/app/cooperatives': typeof AppCooperativesRoute
  '/app/custom-kpis': typeof AppCustomKpisRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/debug-auth': typeof AppDebugAuthRoute
  '/app/federations': typeof AppFederationsRoute
  '/app/financial-statement': typeof AppFinancialStatementRoute
  '/app/invitations': typeof AppInvitationsRoute
  '/app/members': typeof AppMembersRoute
  '/app/non-financial-data': typeof AppNonFinancialDataRoute
  '/app/profile': typeof AppProfileRoute
  '/app/questionnaire-templates': typeof AppQuestionnaireTemplatesRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/submissions': typeof AppSubmissionsRoute
  '/app/users': typeof AppUsersRouteWithChildren
  '/print/ministry': typeof PrintMinistryRoute
  '/app/': typeof AppIndexRoute
  '/app/cooperative-members/$cooperativeId': typeof AppCooperativeMembersCooperativeIdRoute
  '/app/cooperative-profile/$cooperativeId': typeof AppCooperativeProfileCooperativeIdRoute
  '/app/cooperative/$cooperativeId': typeof AppCooperativeCooperativeIdRoute
  '/app/submissions/$id': typeof AppSubmissionsIdRouteWithChildren
  '/app/users/$apexId': typeof AppUsersApexIdRoute
  '/print/apex/$id': typeof PrintApexIdRoute
  '/print/cooperative/$id': typeof PrintCooperativeIdRoute
  '/print/federation/$id': typeof PrintFederationIdRoute
  '/app/users/': typeof AppUsersIndexRoute
  '/app/submissions/$id/manual-entry': typeof AppSubmissionsIdManualEntryRoute
  '/app/submissions/$id/questionnaire': typeof AppSubmissionsIdQuestionnaireRoute
  '/app/submissions/$id/': typeof AppSubmissionsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/apexes': typeof AppApexesRoute
  '/app/audit': typeof AppAuditRoute
  '/app/basic-analytics': typeof AppBasicAnalyticsRoute
  '/app/basic-benchmarking': typeof AppBasicBenchmarkingRoute
  '/app/benchmarking': typeof AppBenchmarkingRoute
  '/app/cooperatives': typeof AppCooperativesRoute
  '/app/custom-kpis': typeof AppCustomKpisRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/debug-auth': typeof AppDebugAuthRoute
  '/app/federations': typeof AppFederationsRoute
  '/app/financial-statement': typeof AppFinancialStatementRoute
  '/app/invitations': typeof AppInvitationsRoute
  '/app/members': typeof AppMembersRoute
  '/app/non-financial-data': typeof AppNonFinancialDataRoute
  '/app/profile': typeof AppProfileRoute
  '/app/questionnaire-templates': typeof AppQuestionnaireTemplatesRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/submissions': typeof AppSubmissionsRoute
  '/print/ministry': typeof PrintMinistryRoute
  '/app': typeof AppIndexRoute
  '/app/cooperative-members/$cooperativeId': typeof AppCooperativeMembersCooperativeIdRoute
  '/app/cooperative-profile/$cooperativeId': typeof AppCooperativeProfileCooperativeIdRoute
  '/app/cooperative/$cooperativeId': typeof AppCooperativeCooperativeIdRoute
  '/app/users/$apexId': typeof AppUsersApexIdRoute
  '/print/apex/$id': typeof PrintApexIdRoute
  '/print/cooperative/$id': typeof PrintCooperativeIdRoute
  '/print/federation/$id': typeof PrintFederationIdRoute
  '/app/users': typeof AppUsersIndexRoute
  '/app/submissions/$id/manual-entry': typeof AppSubmissionsIdManualEntryRoute
  '/app/submissions/$id/questionnaire': typeof AppSubmissionsIdQuestionnaireRoute
  '/app/submissions/$id': typeof AppSubmissionsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/apexes': typeof AppApexesRoute
  '/app/audit': typeof AppAuditRoute
  '/app/basic-analytics': typeof AppBasicAnalyticsRoute
  '/app/basic-benchmarking': typeof AppBasicBenchmarkingRoute
  '/app/benchmarking': typeof AppBenchmarkingRoute
  '/app/cooperatives': typeof AppCooperativesRoute
  '/app/custom-kpis': typeof AppCustomKpisRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/debug-auth': typeof AppDebugAuthRoute
  '/app/federations': typeof AppFederationsRoute
  '/app/financial-statement': typeof AppFinancialStatementRoute
  '/app/invitations': typeof AppInvitationsRoute
  '/app/members': typeof AppMembersRoute
  '/app/non-financial-data': typeof AppNonFinancialDataRoute
  '/app/profile': typeof AppProfileRoute
  '/app/questionnaire-templates': typeof AppQuestionnaireTemplatesRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/submissions': typeof AppSubmissionsRoute
  '/app/users': typeof AppUsersRouteWithChildren
  '/print/ministry': typeof PrintMinistryRoute
  '/app/': typeof AppIndexRoute
  '/app/cooperative-members/$cooperativeId': typeof AppCooperativeMembersCooperativeIdRoute
  '/app/cooperative-profile/$cooperativeId': typeof AppCooperativeProfileCooperativeIdRoute
  '/app/cooperative/$cooperativeId': typeof AppCooperativeCooperativeIdRoute
  '/app/submissions_/$id': typeof AppSubmissionsIdRouteWithChildren
  '/app/users/$apexId': typeof AppUsersApexIdRoute
  '/print/apex/$id': typeof PrintApexIdRoute
  '/print/cooperative/$id': typeof PrintCooperativeIdRoute
  '/print/federation/$id': typeof PrintFederationIdRoute
  '/app/users/': typeof AppUsersIndexRoute
  '/app/submissions_/$id/manual-entry': typeof AppSubmissionsIdManualEntryRoute
  '/app/submissions_/$id/questionnaire': typeof AppSubmissionsIdQuestionnaireRoute
  '/app/submissions_/$id/': typeof AppSubmissionsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/unauthorized'
    | '/app/analytics'
    | '/app/apexes'
    | '/app/audit'
    | '/app/basic-analytics'
    | '/app/basic-benchmarking'
    | '/app/benchmarking'
    | '/app/cooperatives'
    | '/app/custom-kpis'
    | '/app/dashboard'
    | '/app/debug-auth'
    | '/app/federations'
    | '/app/financial-statement'
    | '/app/invitations'
    | '/app/members'
    | '/app/non-financial-data'
    | '/app/profile'
    | '/app/questionnaire-templates'
    | '/app/reports'
    | '/app/settings'
    | '/app/submissions'
    | '/app/users'
    | '/print/ministry'
    | '/app/'
    | '/app/cooperative-members/$cooperativeId'
    | '/app/cooperative-profile/$cooperativeId'
    | '/app/cooperative/$cooperativeId'
    | '/app/submissions/$id'
    | '/app/users/$apexId'
    | '/print/apex/$id'
    | '/print/cooperative/$id'
    | '/print/federation/$id'
    | '/app/users/'
    | '/app/submissions/$id/manual-entry'
    | '/app/submissions/$id/questionnaire'
    | '/app/submissions/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/unauthorized'
    | '/app/analytics'
    | '/app/apexes'
    | '/app/audit'
    | '/app/basic-analytics'
    | '/app/basic-benchmarking'
    | '/app/benchmarking'
    | '/app/cooperatives'
    | '/app/custom-kpis'
    | '/app/dashboard'
    | '/app/debug-auth'
    | '/app/federations'
    | '/app/financial-statement'
    | '/app/invitations'
    | '/app/members'
    | '/app/non-financial-data'
    | '/app/profile'
    | '/app/questionnaire-templates'
    | '/app/reports'
    | '/app/settings'
    | '/app/submissions'
    | '/print/ministry'
    | '/app'
    | '/app/cooperative-members/$cooperativeId'
    | '/app/cooperative-profile/$cooperativeId'
    | '/app/cooperative/$cooperativeId'
    | '/app/users/$apexId'
    | '/print/apex/$id'
    | '/print/cooperative/$id'
    | '/print/federation/$id'
    | '/app/users'
    | '/app/submissions/$id/manual-entry'
    | '/app/submissions/$id/questionnaire'
    | '/app/submissions/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/unauthorized'
    | '/app/analytics'
    | '/app/apexes'
    | '/app/audit'
    | '/app/basic-analytics'
    | '/app/basic-benchmarking'
    | '/app/benchmarking'
    | '/app/cooperatives'
    | '/app/custom-kpis'
    | '/app/dashboard'
    | '/app/debug-auth'
    | '/app/federations'
    | '/app/financial-statement'
    | '/app/invitations'
    | '/app/members'
    | '/app/non-financial-data'
    | '/app/profile'
    | '/app/questionnaire-templates'
    | '/app/reports'
    | '/app/settings'
    | '/app/submissions'
    | '/app/users'
    | '/print/ministry'
    | '/app/'
    | '/app/cooperative-members/$cooperativeId'
    | '/app/cooperative-profile/$cooperativeId'
    | '/app/cooperative/$cooperativeId'
    | '/app/submissions_/$id'
    | '/app/users/$apexId'
    | '/print/apex/$id'
    | '/print/cooperative/$id'
    | '/print/federation/$id'
    | '/app/users/'
    | '/app/submissions_/$id/manual-entry'
    | '/app/submissions_/$id/questionnaire'
    | '/app/submissions_/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  PrintMinistryRoute: typeof PrintMinistryRoute
  PrintApexIdRoute: typeof PrintApexIdRoute
  PrintCooperativeIdRoute: typeof PrintCooperativeIdRoute
  PrintFederationIdRoute: typeof PrintFederationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/print/ministry': {
      id: '/print/ministry'
      path: '/print/ministry'
      fullPath: '/print/ministry'
      preLoaderRoute: typeof PrintMinistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/submissions': {
      id: '/app/submissions'
      path: '/submissions'
      fullPath: '/app/submissions'
      preLoaderRoute: typeof AppSubmissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/questionnaire-templates': {
      id: '/app/questionnaire-templates'
      path: '/questionnaire-templates'
      fullPath: '/app/questionnaire-templates'
      preLoaderRoute: typeof AppQuestionnaireTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/non-financial-data': {
      id: '/app/non-financial-data'
      path: '/non-financial-data'
      fullPath: '/app/non-financial-data'
      preLoaderRoute: typeof AppNonFinancialDataRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/members': {
      id: '/app/members'
      path: '/members'
      fullPath: '/app/members'
      preLoaderRoute: typeof AppMembersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/invitations': {
      id: '/app/invitations'
      path: '/invitations'
      fullPath: '/app/invitations'
      preLoaderRoute: typeof AppInvitationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/financial-statement': {
      id: '/app/financial-statement'
      path: '/financial-statement'
      fullPath: '/app/financial-statement'
      preLoaderRoute: typeof AppFinancialStatementRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/federations': {
      id: '/app/federations'
      path: '/federations'
      fullPath: '/app/federations'
      preLoaderRoute: typeof AppFederationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/debug-auth': {
      id: '/app/debug-auth'
      path: '/debug-auth'
      fullPath: '/app/debug-auth'
      preLoaderRoute: typeof AppDebugAuthRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/custom-kpis': {
      id: '/app/custom-kpis'
      path: '/custom-kpis'
      fullPath: '/app/custom-kpis'
      preLoaderRoute: typeof AppCustomKpisRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cooperatives': {
      id: '/app/cooperatives'
      path: '/cooperatives'
      fullPath: '/app/cooperatives'
      preLoaderRoute: typeof AppCooperativesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/benchmarking': {
      id: '/app/benchmarking'
      path: '/benchmarking'
      fullPath: '/app/benchmarking'
      preLoaderRoute: typeof AppBenchmarkingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/basic-benchmarking': {
      id: '/app/basic-benchmarking'
      path: '/basic-benchmarking'
      fullPath: '/app/basic-benchmarking'
      preLoaderRoute: typeof AppBasicBenchmarkingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/basic-analytics': {
      id: '/app/basic-analytics'
      path: '/basic-analytics'
      fullPath: '/app/basic-analytics'
      preLoaderRoute: typeof AppBasicAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/apexes': {
      id: '/app/apexes'
      path: '/apexes'
      fullPath: '/app/apexes'
      preLoaderRoute: typeof AppApexesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/users/': {
      id: '/app/users/'
      path: '/'
      fullPath: '/app/users/'
      preLoaderRoute: typeof AppUsersIndexRouteImport
      parentRoute: typeof AppUsersRoute
    }
    '/print/federation/$id': {
      id: '/print/federation/$id'
      path: '/print/federation/$id'
      fullPath: '/print/federation/$id'
      preLoaderRoute: typeof PrintFederationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/cooperative/$id': {
      id: '/print/cooperative/$id'
      path: '/print/cooperative/$id'
      fullPath: '/print/cooperative/$id'
      preLoaderRoute: typeof PrintCooperativeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/apex/$id': {
      id: '/print/apex/$id'
      path: '/print/apex/$id'
      fullPath: '/print/apex/$id'
      preLoaderRoute: typeof PrintApexIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/users/$apexId': {
      id: '/app/users/$apexId'
      path: '/$apexId'
      fullPath: '/app/users/$apexId'
      preLoaderRoute: typeof AppUsersApexIdRouteImport
      parentRoute: typeof AppUsersRoute
    }
    '/app/submissions_/$id': {
      id: '/app/submissions_/$id'
      path: '/submissions/$id'
      fullPath: '/app/submissions/$id'
      preLoaderRoute: typeof AppSubmissionsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cooperative/$cooperativeId': {
      id: '/app/cooperative/$cooperativeId'
      path: '/cooperative/$cooperativeId'
      fullPath: '/app/cooperative/$cooperativeId'
      preLoaderRoute: typeof AppCooperativeCooperativeIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cooperative-profile/$cooperativeId': {
      id: '/app/cooperative-profile/$cooperativeId'
      path: '/cooperative-profile/$cooperativeId'
      fullPath: '/app/cooperative-profile/$cooperativeId'
      preLoaderRoute: typeof AppCooperativeProfileCooperativeIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cooperative-members/$cooperativeId': {
      id: '/app/cooperative-members/$cooperativeId'
      path: '/cooperative-members/$cooperativeId'
      fullPath: '/app/cooperative-members/$cooperativeId'
      preLoaderRoute: typeof AppCooperativeMembersCooperativeIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/submissions_/$id/': {
      id: '/app/submissions_/$id/'
      path: '/'
      fullPath: '/app/submissions/$id/'
      preLoaderRoute: typeof AppSubmissionsIdIndexRouteImport
      parentRoute: typeof AppSubmissionsIdRoute
    }
    '/app/submissions_/$id/questionnaire': {
      id: '/app/submissions_/$id/questionnaire'
      path: '/questionnaire'
      fullPath: '/app/submissions/$id/questionnaire'
      preLoaderRoute: typeof AppSubmissionsIdQuestionnaireRouteImport
      parentRoute: typeof AppSubmissionsIdRoute
    }
    '/app/submissions_/$id/manual-entry': {
      id: '/app/submissions_/$id/manual-entry'
      path: '/manual-entry'
      fullPath: '/app/submissions/$id/manual-entry'
      preLoaderRoute: typeof AppSubmissionsIdManualEntryRouteImport
      parentRoute: typeof AppSubmissionsIdRoute
    }
  }
}

interface AppUsersRouteChildren {
  AppUsersApexIdRoute: typeof AppUsersApexIdRoute
  AppUsersIndexRoute: typeof AppUsersIndexRoute
}

const AppUsersRouteChildren: AppUsersRouteChildren = {
  AppUsersApexIdRoute: AppUsersApexIdRoute,
  AppUsersIndexRoute: AppUsersIndexRoute,
}

const AppUsersRouteWithChildren = AppUsersRoute._addFileChildren(
  AppUsersRouteChildren,
)

interface AppSubmissionsIdRouteChildren {
  AppSubmissionsIdManualEntryRoute: typeof AppSubmissionsIdManualEntryRoute
  AppSubmissionsIdQuestionnaireRoute: typeof AppSubmissionsIdQuestionnaireRoute
  AppSubmissionsIdIndexRoute: typeof AppSubmissionsIdIndexRoute
}

const AppSubmissionsIdRouteChildren: AppSubmissionsIdRouteChildren = {
  AppSubmissionsIdManualEntryRoute: AppSubmissionsIdManualEntryRoute,
  AppSubmissionsIdQuestionnaireRoute: AppSubmissionsIdQuestionnaireRoute,
  AppSubmissionsIdIndexRoute: AppSubmissionsIdIndexRoute,
}

const AppSubmissionsIdRouteWithChildren =
  AppSubmissionsIdRoute._addFileChildren(AppSubmissionsIdRouteChildren)

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppApexesRoute: typeof AppApexesRoute
  AppAuditRoute: typeof AppAuditRoute
  AppBasicAnalyticsRoute: typeof AppBasicAnalyticsRoute
  AppBasicBenchmarkingRoute: typeof AppBasicBenchmarkingRoute
  AppBenchmarkingRoute: typeof AppBenchmarkingRoute
  AppCooperativesRoute: typeof AppCooperativesRoute
  AppCustomKpisRoute: typeof AppCustomKpisRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDebugAuthRoute: typeof AppDebugAuthRoute
  AppFederationsRoute: typeof AppFederationsRoute
  AppFinancialStatementRoute: typeof AppFinancialStatementRoute
  AppInvitationsRoute: typeof AppInvitationsRoute
  AppMembersRoute: typeof AppMembersRoute
  AppNonFinancialDataRoute: typeof AppNonFinancialDataRoute
  AppProfileRoute: typeof AppProfileRoute
  AppQuestionnaireTemplatesRoute: typeof AppQuestionnaireTemplatesRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSubmissionsRoute: typeof AppSubmissionsRoute
  AppUsersRoute: typeof AppUsersRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppCooperativeMembersCooperativeIdRoute: typeof AppCooperativeMembersCooperativeIdRoute
  AppCooperativeProfileCooperativeIdRoute: typeof AppCooperativeProfileCooperativeIdRoute
  AppCooperativeCooperativeIdRoute: typeof AppCooperativeCooperativeIdRoute
  AppSubmissionsIdRoute: typeof AppSubmissionsIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppApexesRoute: AppApexesRoute,
  AppAuditRoute: AppAuditRoute,
  AppBasicAnalyticsRoute: AppBasicAnalyticsRoute,
  AppBasicBenchmarkingRoute: AppBasicBenchmarkingRoute,
  AppBenchmarkingRoute: AppBenchmarkingRoute,
  AppCooperativesRoute: AppCooperativesRoute,
  AppCustomKpisRoute: AppCustomKpisRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDebugAuthRoute: AppDebugAuthRoute,
  AppFederationsRoute: AppFederationsRoute,
  AppFinancialStatementRoute: AppFinancialStatementRoute,
  AppInvitationsRoute: AppInvitationsRoute,
  AppMembersRoute: AppMembersRoute,
  AppNonFinancialDataRoute: AppNonFinancialDataRoute,
  AppProfileRoute: AppProfileRoute,
  AppQuestionnaireTemplatesRoute: AppQuestionnaireTemplatesRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSubmissionsRoute: AppSubmissionsRoute,
  AppUsersRoute: AppUsersRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppCooperativeMembersCooperativeIdRoute:
    AppCooperativeMembersCooperativeIdRoute,
  AppCooperativeProfileCooperativeIdRoute:
    AppCooperativeProfileCooperativeIdRoute,
  AppCooperativeCooperativeIdRoute: AppCooperativeCooperativeIdRoute,
  AppSubmissionsIdRoute: AppSubmissionsIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  PrintMinistryRoute: PrintMinistryRoute,
  PrintApexIdRoute: PrintApexIdRoute,
  PrintCooperativeIdRoute: PrintCooperativeIdRoute,
  PrintFederationIdRoute: PrintFederationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
