parent=base
import=common/keycloak

styles=css/styles.css
scripts=js/login.js
favicon=img/coopdatalogo.jpg
meta=viewport==width=device-width,initial-scale=1

# Custom properties
kcFormGroupClass=form-group
kcLabelClass=kc-label
kcInputClass=form-control
kcButtonClass=btn
kcButtonPrimaryClass=btn-primary
kcButtonBlockClass=btn-block
kcButtonLargeClass=btn-lg
kcFormPasswordVisibilityButtonClass=btn btn-link
kcInputErrorMessageClass=alert-error
kcRegisterClass=login-pf-register
kcFormSocialAccountSectionClass=login-pf-social-section
kcFormSocialAccountListClass=login-pf-social
kcFormSocialAccountListButtonClass=login-pf-social-link
kcFormSocialAccountGridItem=kc-social-grid-item
kcFormOptionsWrapperClass=kc-form-options-wrapper
kcFormSettingClass=kc-form-setting
