/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AppUsersRouteImport } from './routes/app.users'
import { Route as AppSubmissionsRouteImport } from './routes/app.submissions'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppNonFinancialDataRouteImport } from './routes/app.non-financial-data'
import { Route as AppIntegrationsRouteImport } from './routes/app.integrations'
import { Route as AppFinancialStatementRouteImport } from './routes/app.financial-statement'
import { Route as AppDataCollectionRouteImport } from './routes/app.data-collection'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCooperativesRouteImport } from './routes/app.cooperatives'
import { Route as AppComplianceRouteImport } from './routes/app.compliance'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSubmissionsRoute = AppSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNonFinancialDataRoute = AppNonFinancialDataRouteImport.update({
  id: '/non-financial-data',
  path: '/non-financial-data',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppFinancialStatementRoute = AppFinancialStatementRouteImport.update({
  id: '/financial-statement',
  path: '/financial-statement',
  getParentRoute: () => AppRoute,
} as any)
const AppDataCollectionRoute = AppDataCollectionRouteImport.update({
  id: '/data-collection',
  path: '/data-collection',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCooperativesRoute = AppCooperativesRouteImport.update({
  id: '/cooperatives',
  path: '/cooperatives',
  getParentRoute: () => AppRoute,
} as any)
const AppComplianceRoute = AppComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/compliance': typeof AppComplianceRoute
  '/app/cooperatives': typeof AppCooperativesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/data-collection': typeof AppDataCollectionRoute
  '/app/financial-statement': typeof AppFinancialStatementRoute
  '/app/integrations': typeof AppIntegrationsRoute
  '/app/non-financial-data': typeof AppNonFinancialDataRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/submissions': typeof AppSubmissionsRoute
  '/app/users': typeof AppUsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/compliance': typeof AppComplianceRoute
  '/app/cooperatives': typeof AppCooperativesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/data-collection': typeof AppDataCollectionRoute
  '/app/financial-statement': typeof AppFinancialStatementRoute
  '/app/integrations': typeof AppIntegrationsRoute
  '/app/non-financial-data': typeof AppNonFinancialDataRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/submissions': typeof AppSubmissionsRoute
  '/app/users': typeof AppUsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/compliance': typeof AppComplianceRoute
  '/app/cooperatives': typeof AppCooperativesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/data-collection': typeof AppDataCollectionRoute
  '/app/financial-statement': typeof AppFinancialStatementRoute
  '/app/integrations': typeof AppIntegrationsRoute
  '/app/non-financial-data': typeof AppNonFinancialDataRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/submissions': typeof AppSubmissionsRoute
  '/app/users': typeof AppUsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/analytics'
    | '/app/compliance'
    | '/app/cooperatives'
    | '/app/dashboard'
    | '/app/data-collection'
    | '/app/financial-statement'
    | '/app/integrations'
    | '/app/non-financial-data'
    | '/app/profile'
    | '/app/reports'
    | '/app/settings'
    | '/app/submissions'
    | '/app/users'
    | '/auth/login'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/analytics'
    | '/app/compliance'
    | '/app/cooperatives'
    | '/app/dashboard'
    | '/app/data-collection'
    | '/app/financial-statement'
    | '/app/integrations'
    | '/app/non-financial-data'
    | '/app/profile'
    | '/app/reports'
    | '/app/settings'
    | '/app/submissions'
    | '/app/users'
    | '/auth/login'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/analytics'
    | '/app/compliance'
    | '/app/cooperatives'
    | '/app/dashboard'
    | '/app/data-collection'
    | '/app/financial-statement'
    | '/app/integrations'
    | '/app/non-financial-data'
    | '/app/profile'
    | '/app/reports'
    | '/app/settings'
    | '/app/submissions'
    | '/app/users'
    | '/auth/login'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/submissions': {
      id: '/app/submissions'
      path: '/submissions'
      fullPath: '/app/submissions'
      preLoaderRoute: typeof AppSubmissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/non-financial-data': {
      id: '/app/non-financial-data'
      path: '/non-financial-data'
      fullPath: '/app/non-financial-data'
      preLoaderRoute: typeof AppNonFinancialDataRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/integrations': {
      id: '/app/integrations'
      path: '/integrations'
      fullPath: '/app/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/financial-statement': {
      id: '/app/financial-statement'
      path: '/financial-statement'
      fullPath: '/app/financial-statement'
      preLoaderRoute: typeof AppFinancialStatementRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/data-collection': {
      id: '/app/data-collection'
      path: '/data-collection'
      fullPath: '/app/data-collection'
      preLoaderRoute: typeof AppDataCollectionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cooperatives': {
      id: '/app/cooperatives'
      path: '/cooperatives'
      fullPath: '/app/cooperatives'
      preLoaderRoute: typeof AppCooperativesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/compliance': {
      id: '/app/compliance'
      path: '/compliance'
      fullPath: '/app/compliance'
      preLoaderRoute: typeof AppComplianceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppComplianceRoute: typeof AppComplianceRoute
  AppCooperativesRoute: typeof AppCooperativesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDataCollectionRoute: typeof AppDataCollectionRoute
  AppFinancialStatementRoute: typeof AppFinancialStatementRoute
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppNonFinancialDataRoute: typeof AppNonFinancialDataRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSubmissionsRoute: typeof AppSubmissionsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppComplianceRoute: AppComplianceRoute,
  AppCooperativesRoute: AppCooperativesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDataCollectionRoute: AppDataCollectionRoute,
  AppFinancialStatementRoute: AppFinancialStatementRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppNonFinancialDataRoute: AppNonFinancialDataRoute,
  AppProfileRoute: AppProfileRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSubmissionsRoute: AppSubmissionsRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
