apiVersion: 1
policies:
  - orgId: 1
    receiver: Slack Channel
    group_by: ['alertname', 'severity', 'service']
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    routes:
      - receiver: Discord Channel
        matchers:
          - severity = critical
